// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/task.service.proto

package task_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	From                 string   `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	StartDate            int64    `protobuf:"varint,6,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate              int64    `protobuf:"varint,7,opt,name=endDate,proto3" json:"endDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6d7488e6b96f81d, []int{0}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Task) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Task) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Task) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Task) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *Task) GetEndDate() int64 {
	if m != nil {
		return m.EndDate
	}
	return 0
}

type Tasks struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tasks) Reset()         { *m = Tasks{} }
func (m *Tasks) String() string { return proto.CompactTextString(m) }
func (*Tasks) ProtoMessage()    {}
func (*Tasks) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6d7488e6b96f81d, []int{1}
}
func (m *Tasks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tasks.Unmarshal(m, b)
}
func (m *Tasks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tasks.Marshal(b, m, deterministic)
}
func (m *Tasks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tasks.Merge(m, src)
}
func (m *Tasks) XXX_Size() int {
	return xxx_messageInfo_Tasks.Size(m)
}
func (m *Tasks) XXX_DiscardUnknown() {
	xxx_messageInfo_Tasks.DiscardUnknown(m)
}

var xxx_messageInfo_Tasks proto.InternalMessageInfo

func (m *Tasks) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type FindOneParams struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOneParams) Reset()         { *m = FindOneParams{} }
func (m *FindOneParams) String() string { return proto.CompactTextString(m) }
func (*FindOneParams) ProtoMessage()    {}
func (*FindOneParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6d7488e6b96f81d, []int{2}
}
func (m *FindOneParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneParams.Unmarshal(m, b)
}
func (m *FindOneParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneParams.Marshal(b, m, deterministic)
}
func (m *FindOneParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneParams.Merge(m, src)
}
func (m *FindOneParams) XXX_Size() int {
	return xxx_messageInfo_FindOneParams.Size(m)
}
func (m *FindOneParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneParams.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneParams proto.InternalMessageInfo

func (m *FindOneParams) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindAllParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllParams) Reset()         { *m = FindAllParams{} }
func (m *FindAllParams) String() string { return proto.CompactTextString(m) }
func (*FindAllParams) ProtoMessage()    {}
func (*FindAllParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6d7488e6b96f81d, []int{3}
}
func (m *FindAllParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllParams.Unmarshal(m, b)
}
func (m *FindAllParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllParams.Marshal(b, m, deterministic)
}
func (m *FindAllParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllParams.Merge(m, src)
}
func (m *FindAllParams) XXX_Size() int {
	return xxx_messageInfo_FindAllParams.Size(m)
}
func (m *FindAllParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllParams.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllParams proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Task)(nil), "Task")
	proto.RegisterType((*Tasks)(nil), "Tasks")
	proto.RegisterType((*FindOneParams)(nil), "FindOneParams")
	proto.RegisterType((*FindAllParams)(nil), "FindAllParams")
}

func init() { proto.RegisterFile("protos/task.service.proto", fileDescriptor_f6d7488e6b96f81d) }

var fileDescriptor_f6d7488e6b96f81d = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xd1, 0x4a, 0xec, 0x30,
	0x10, 0x86, 0x49, 0xdb, 0xb4, 0xec, 0x2c, 0x67, 0x0f, 0x0c, 0x5e, 0xc4, 0x55, 0xb0, 0x16, 0x2f,
	0x7a, 0x55, 0x61, 0x7d, 0x82, 0x05, 0xf1, 0x56, 0x89, 0xbe, 0x40, 0xdc, 0x46, 0x08, 0x9b, 0x4d,
	0x24, 0x19, 0x7c, 0x20, 0x9f, 0x54, 0x92, 0xec, 0x2a, 0x7a, 0xd7, 0xff, 0x9b, 0x9f, 0xaf, 0x99,
	0x81, 0xf3, 0xf7, 0xe0, 0xc9, 0xc7, 0x5b, 0x52, 0x71, 0x3f, 0x45, 0x1d, 0x3e, 0xcc, 0x4e, 0x4f,
	0x99, 0x0d, 0x9f, 0x0c, 0x9a, 0x17, 0x15, 0xf7, 0xb8, 0x82, 0xca, 0xcc, 0x82, 0xf5, 0x6c, 0xe4,
	0xb2, 0x32, 0x33, 0x9e, 0x01, 0x27, 0x43, 0x56, 0x8b, 0xaa, 0x67, 0xe3, 0x42, 0x96, 0x80, 0x02,
	0xba, 0x9d, 0x77, 0xa4, 0x1d, 0x89, 0x3a, 0xf3, 0x53, 0x44, 0x84, 0xe6, 0x2d, 0xf8, 0x83, 0x68,
	0x32, 0xce, 0xdf, 0xc9, 0x49, 0x5e, 0xf0, 0x4c, 0x2a, 0xf2, 0x78, 0x09, 0x8b, 0x48, 0x2a, 0xd0,
	0xbd, 0x22, 0x2d, 0xda, 0x9e, 0x8d, 0xb5, 0xfc, 0x01, 0xc9, 0xad, 0xdd, 0x9c, 0x67, 0x5d, 0x9e,
	0x9d, 0xe2, 0x70, 0x03, 0x3c, 0xbd, 0x31, 0xe2, 0x05, 0xf0, 0xb4, 0x43, 0x14, 0xac, 0xaf, 0xc7,
	0xe5, 0x86, 0x4f, 0x09, 0xcb, 0xc2, 0x86, 0x2b, 0xf8, 0xf7, 0x60, 0xdc, 0xfc, 0xe8, 0xf4, 0x93,
	0x0a, 0xea, 0x10, 0xff, 0xae, 0x34, 0xfc, 0x2f, 0x85, 0xad, 0xb5, 0xa5, 0xb0, 0x91, 0xb0, 0x4c,
	0x82, 0xe7, 0x72, 0x11, 0xec, 0xa1, 0x3b, 0x0a, 0x70, 0x35, 0xfd, 0x52, 0xad, 0xcb, 0x9f, 0xf0,
	0xba, 0x34, 0xb6, 0xd6, 0x1e, 0x1b, 0xdf, 0xae, 0x75, 0x9b, 0x1b, 0xf1, 0xb5, 0xcd, 0x77, 0xbd,
	0xfb, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x53, 0x50, 0x2f, 0x74, 0x01, 0x00, 0x00,
}
